package desafio2.views;

import desafio2.controllers.CtrlAuthors;
import desafio2.controllers.CtrlBooks;
import desafio2.controllers.CtrlCDs;
import desafio2.controllers.CtrlEditorials;
import desafio2.controllers.CtrlMagazines;
import desafio2.helpers.GenerateCode;
import desafio2.helpers.Validators;
import desafio2.models.Author;
import desafio2.models.Book;
import desafio2.models.Cd;
import desafio2.models.Editorial;
import desafio2.models.Gender;
import desafio2.models.Magazine;
import desafio2.models.Periodicity;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class FrmCreateCDs extends javax.swing.JPanel {
    private JPanel layoutPanel;
    private CtrlCDs cdsController;
    private CtrlAuthors artistsController;    
    private List<Gender> genders;
    private List<Author> artists;

    public FrmCreateCDs(JPanel layoutPanel) {
        initComponents();
        
        cdsController = new CtrlCDs();
        artistsController = new CtrlAuthors();
        
        getGenders();
        getArtists();
        
        this.layoutPanel = layoutPanel;
        
        handleEditorialMode();
        
        Validators.allowNumbers(numCancionesTxt, 5);
        Validators.allowNumbers(unidadesTxt, 5);
    }
    
    private void setLayoutContent(JPanel content) {
        layoutPanel.removeAll();
        layoutPanel.add(content, BorderLayout.CENTER);
        layoutPanel.revalidate();
        layoutPanel.repaint();
    }
    
    private void getGenders() {
        genders = cdsController.getGenders();
        
        genderCb.removeAllItems();
        genderCb.addItem("Selecciona el género");
        
        for (int i = 0; i < genders.size(); i++) {
            Gender gender = genders.get(i);
            
            genderCb.addItem(gender.getGenero());
        }
    }
    
    private void getArtists() {
        artists = artistsController.getArtists();
        
        artistCb.removeAllItems();
        artistCb.addItem("Selecciona un artista");
        
        for (int i = 0; i < artists.size(); i++) {
            Author author = artists.get(i);
            
            artistCb.addItem(author.getNombre());
        }
    }
    
    private void handleEditorialMode() {
       boolean existentEditorial = existentArtistRb.isSelected();
       boolean newEditorial = newArtistRb.isSelected();
       
       artistTxt.setVisible(newEditorial);
       artistCb.setVisible(existentEditorial);
    }
    
    private int handleGenderCreation() {
        int genderId = 0;
        
        for (Gender g : genders) {
            if (g.getGenero().equals(genderCb.getSelectedItem())) {
                genderId = g.getId();
                break;
            }
        }
        
        return genderId;
    }
    
    private int handleArtistCreation () {
        int artistId = 0;
        boolean existentArtist = existentArtistRb.isSelected();
        
        if (existentArtist) {
            for (Author a : artists) {
                if (a.getNombre().equals(artistCb.getSelectedItem())) {
                    artistId = a.getId();
                    break;
                }
            }
            
        } else {
            String artistName = artistTxt.getText().trim();
            
            if(artistName.length() == 0) {
                JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
                return artistId;
            }
            
            Author author = new Author();
            
            author.setNombre(artistName);
            author.setTipoCreadorId(2);
            
            boolean ok = artistsController.createAuthor(author);
            if(!ok) return artistId;
            
            Author newAuthor = artistsController.getLatestAuthor();
            
            artistId = newAuthor.getId();
        }
        
        return artistId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorGroup = new javax.swing.ButtonGroup();
        editorialGroup = new javax.swing.ButtonGroup();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        genderCb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        existentArtistRb = new javax.swing.JRadioButton();
        artistCb = new javax.swing.JComboBox<>();
        newArtistRb = new javax.swing.JRadioButton();
        artistTxt = new javax.swing.JTextField();
        tituloTxt = new javax.swing.JTextField();
        numCancionesTxt = new javax.swing.JTextField();
        unidadesTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        duracionTxt = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1100, 690));
        setMinimumSize(new java.awt.Dimension(1100, 690));
        setPreferredSize(new java.awt.Dimension(1100, 690));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Género:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Título:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        genderCb.setBackground(new java.awt.Color(255, 255, 255));
        genderCb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        genderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genderCb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jPanel1.add(genderCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 480, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Número de canciones:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 153, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Regresar");
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, 140, 40));

        saveBtn.setBackground(new java.awt.Color(0, 153, 255));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Guardar");
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 140, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nuevo CD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Artista");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        existentArtistRb.setBackground(new java.awt.Color(255, 255, 255));
        editorialGroup.add(existentArtistRb);
        existentArtistRb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        existentArtistRb.setForeground(new java.awt.Color(102, 102, 102));
        existentArtistRb.setSelected(true);
        existentArtistRb.setText("Artista existente");
        existentArtistRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existentArtistRbActionPerformed(evt);
            }
        });
        jPanel1.add(existentArtistRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        artistCb.setBackground(new java.awt.Color(255, 255, 255));
        artistCb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        artistCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        artistCb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jPanel1.add(artistCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 480, 30));

        newArtistRb.setBackground(new java.awt.Color(255, 255, 255));
        editorialGroup.add(newArtistRb);
        newArtistRb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newArtistRb.setForeground(new java.awt.Color(102, 102, 102));
        newArtistRb.setText("Crear nuevo artista");
        newArtistRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newArtistRbActionPerformed(evt);
            }
        });
        jPanel1.add(newArtistRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        artistTxt.setBackground(new java.awt.Color(255, 255, 255));
        artistTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        artistTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        artistTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                artistTxtKeyReleased(evt);
            }
        });
        jPanel1.add(artistTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 480, 30));

        tituloTxt.setBackground(new java.awt.Color(255, 255, 255));
        tituloTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tituloTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        tituloTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tituloTxtKeyReleased(evt);
            }
        });
        jPanel1.add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 480, 30));

        numCancionesTxt.setBackground(new java.awt.Color(255, 255, 255));
        numCancionesTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        numCancionesTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        numCancionesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numCancionesTxtKeyReleased(evt);
            }
        });
        jPanel1.add(numCancionesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 480, 30));

        unidadesTxt.setBackground(new java.awt.Color(255, 255, 255));
        unidadesTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        unidadesTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        unidadesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unidadesTxtKeyReleased(evt);
            }
        });
        jPanel1.add(unidadesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 480, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Unidades disponibles:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Duración:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        duracionTxt.setBackground(new java.awt.Color(255, 255, 255));
        duracionTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        try {
            duracionTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        duracionTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(duracionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 480, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FrmSelectMaterialType form = new FrmSelectMaterialType(layoutPanel);
        setLayoutContent(form);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String titulo = tituloTxt.getText().trim();        
        String numCanciones = numCancionesTxt.getText();
        String unidades = unidadesTxt.getText();
        String duracion = duracionTxt.getText();
        int generoId;
        int artistaId;        
        
        boolean validated = true;
        String[] fields = {titulo, unidades, numCanciones, duracion};
        
        for (int i = 0; i < fields.length; i++) {
            if (fields[i].length() == 0) {
                validated = false;
                break;
            }
        }
        
        if (!validated) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
            return;
        }
        
        generoId = handleGenderCreation();
        artistaId = handleArtistCreation();
        
        if(generoId == 0 || artistaId == 0) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
        }
        
        GenerateCode gc = new GenerateCode("CD");
        
        if(gc.getCode().equals("invalid")) {
            JOptionPane.showMessageDialog(null, "Sucedio un error al crear este registro. Comunicate con el administrador.");
        }
        
        Cd cd = new Cd();

        cd.setCodigo(gc.getCode());
        cd.setTitulo(titulo);
        cd.setDuracion(duracion);
        cd.setGeneroId(generoId);
        cd.setUnidades(Integer.parseInt(unidades));
        cd.setNumero_canciones(Integer.parseInt(numCanciones));
        cd.setTipoMaterialId(3);
        cd.setArtistId(artistaId);
        
        boolean ok = cdsController.createCd(cd);
        
        if(!ok) return;
        
        FrmMaterials form = new FrmMaterials(layoutPanel);
        JOptionPane.showMessageDialog(null, "Material guardado exitosamente");
        
        setLayoutContent(form);
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void existentArtistRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existentArtistRbActionPerformed
        handleEditorialMode();
    }//GEN-LAST:event_existentArtistRbActionPerformed

    private void newArtistRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newArtistRbActionPerformed
        handleEditorialMode();
    }//GEN-LAST:event_newArtistRbActionPerformed

    private void tituloTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tituloTxtKeyReleased
        String text = tituloTxt.getText();
        boolean validLength = Validators.checkTextLength(text, 100);
        boolean validFormat = Validators.matchesRegex(text, Validators.getNoMaliciousCharactersRegex());
        
        if(!validLength) tituloTxt.setText(text.substring(0, 100));
        if (!validFormat) tituloTxt.setText(text.substring(0, text.length() - 1));
    }//GEN-LAST:event_tituloTxtKeyReleased

    private void artistTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_artistTxtKeyReleased
        String text = artistTxt.getText();
        boolean validLength = Validators.checkTextLength(text, 100);
        boolean validFormat = Validators.matchesRegex(text, Validators.getNoMaliciousCharactersRegex());
        
        if(!validLength) artistTxt.setText(text.substring(0, 100));
        if (!validFormat) artistTxt.setText(text.substring(0, text.length() - 1));
    }//GEN-LAST:event_artistTxtKeyReleased

    private void numCancionesTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numCancionesTxtKeyReleased
        
    }//GEN-LAST:event_numCancionesTxtKeyReleased

    private void unidadesTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadesTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadesTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> artistCb;
    private javax.swing.JTextField artistTxt;
    private javax.swing.ButtonGroup authorGroup;
    private javax.swing.JButton backBtn;
    private javax.swing.JFormattedTextField duracionTxt;
    private javax.swing.ButtonGroup editorialGroup;
    private javax.swing.JRadioButton existentArtistRb;
    private javax.swing.JComboBox<String> genderCb;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton newArtistRb;
    private javax.swing.JTextField numCancionesTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField tituloTxt;
    private javax.swing.JTextField unidadesTxt;
    // End of variables declaration//GEN-END:variables
}
