package desafio2.views;

import desafio2.controllers.CtrlAuthors;
import desafio2.controllers.CtrlCDs;
import desafio2.controllers.CtrlDVDs;
import desafio2.helpers.GenerateCode;
import desafio2.helpers.Validators;
import desafio2.models.Author;
import desafio2.models.Cd;
import desafio2.models.Dvd;
import desafio2.models.Gender;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class FrmCreateDVDs extends javax.swing.JPanel {
    private JPanel layoutPanel;
    private CtrlDVDs dvdsController;
    private CtrlAuthors directorsController;    
    private List<Gender> genders;
    private List<Author> directors;

    public FrmCreateDVDs(JPanel layoutPanel) {
        initComponents();
        
        dvdsController = new CtrlDVDs();
        directorsController = new CtrlAuthors();
        
        getGenders();
        getDirectors();
        
        this.layoutPanel = layoutPanel;
        
        handleDirectorMode();
    }
    
    private void setLayoutContent(JPanel content) {
        layoutPanel.removeAll();
        layoutPanel.add(content, BorderLayout.CENTER);
        layoutPanel.revalidate();
        layoutPanel.repaint();
    }
    
    private void getGenders() {
        genders = dvdsController.getGenders();
        
        genderCb.removeAllItems();
        genderCb.addItem("Selecciona el género");
        
        for (int i = 0; i < genders.size(); i++) {
            Gender gender = genders.get(i);
            
            genderCb.addItem(gender.getGenero());
        }
    }
    
    private void getDirectors() {
        directors = directorsController.getDirectors();
        
        directorCb.removeAllItems();
        directorCb.addItem("Selecciona un director");
        
        for (int i = 0; i < directors.size(); i++) {
            Author author = directors.get(i);
            
            directorCb.addItem(author.getNombre());
        }
    }
    
    private void handleDirectorMode() {
       boolean exists = existentDirectorRb.isSelected();
       boolean isNew = newDirectorRb.isSelected();
       
       directorTxt.setVisible(isNew);
       directorCb.setVisible(exists);
    }
    
    private int handleGenderCreation() {
        int genderId = 0;
        
        for (Gender g : genders) {
            if (g.getGenero().equals(genderCb.getSelectedItem())) {
                genderId = g.getId();
                break;
            }
        }
        
        return genderId;
    }
    
    private int handleDirectorCreation () {
        int directorId = 0;
        boolean existentDirector = existentDirectorRb.isSelected();
        
        if (existentDirector) {
            for (Author a : directors) {
                if (a.getNombre().equals(directorCb.getSelectedItem())) {
                    directorId = a.getId();
                    break;
                }
            }
            
        } else {
            String directorName = directorTxt.getText().trim();
            
            if(directorName.length() == 0) {
                JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
                return directorId;
            }
            
            Author author = new Author();
            
            author.setNombre(directorName);
            author.setTipoCreadorId(3);
            
            boolean ok = directorsController.createAuthor(author);
            if(!ok) return directorId;
            
            Author newAuthor = directorsController.getLatestAuthor();
            
            directorId = newAuthor.getId();
        }
        
        return directorId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorGroup = new javax.swing.ButtonGroup();
        editorialGroup = new javax.swing.ButtonGroup();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        genderCb = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        existentDirectorRb = new javax.swing.JRadioButton();
        directorCb = new javax.swing.JComboBox<>();
        newDirectorRb = new javax.swing.JRadioButton();
        directorTxt = new javax.swing.JTextField();
        tituloTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        duracionTxt = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1100, 690));
        setMinimumSize(new java.awt.Dimension(1100, 690));
        setPreferredSize(new java.awt.Dimension(1100, 690));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Género:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Título:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        genderCb.setBackground(new java.awt.Color(255, 255, 255));
        genderCb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        genderCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genderCb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jPanel1.add(genderCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 480, 30));

        backBtn.setBackground(new java.awt.Color(0, 153, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Regresar");
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, 140, 40));

        saveBtn.setBackground(new java.awt.Color(0, 153, 255));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Guardar");
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 140, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nuevo DVD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Director:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        existentDirectorRb.setBackground(new java.awt.Color(255, 255, 255));
        editorialGroup.add(existentDirectorRb);
        existentDirectorRb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        existentDirectorRb.setForeground(new java.awt.Color(102, 102, 102));
        existentDirectorRb.setSelected(true);
        existentDirectorRb.setText("Director existente");
        existentDirectorRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existentDirectorRbActionPerformed(evt);
            }
        });
        jPanel1.add(existentDirectorRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        directorCb.setBackground(new java.awt.Color(255, 255, 255));
        directorCb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        directorCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        directorCb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jPanel1.add(directorCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 480, 30));

        newDirectorRb.setBackground(new java.awt.Color(255, 255, 255));
        editorialGroup.add(newDirectorRb);
        newDirectorRb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newDirectorRb.setForeground(new java.awt.Color(102, 102, 102));
        newDirectorRb.setText("Crear nuevo director");
        newDirectorRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDirectorRbActionPerformed(evt);
            }
        });
        jPanel1.add(newDirectorRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        directorTxt.setBackground(new java.awt.Color(255, 255, 255));
        directorTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        directorTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        directorTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                directorTxtKeyReleased(evt);
            }
        });
        jPanel1.add(directorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 480, 30));

        tituloTxt.setBackground(new java.awt.Color(255, 255, 255));
        tituloTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tituloTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        tituloTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tituloTxtKeyReleased(evt);
            }
        });
        jPanel1.add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 480, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Duración:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        duracionTxt.setBackground(new java.awt.Color(255, 255, 255));
        duracionTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        try {
            duracionTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        duracionTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(duracionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 480, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FrmSelectMaterialType form = new FrmSelectMaterialType(layoutPanel);
        setLayoutContent(form);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String titulo = tituloTxt.getText().trim();        
        String duracion = duracionTxt.getText();
        int generoId;
        int directorId;        
        
        boolean validated = true;
        String[] fields = {titulo, duracion};
        
        for (int i = 0; i < fields.length; i++) {
            if (fields[i].length() == 0) {
                validated = false;
                break;
            }
        }
        
        if (!validated) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
            return;
        }
        
        generoId = handleGenderCreation();
        directorId = handleDirectorCreation();
        
        if(generoId == 0 || directorId == 0) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
        }
        
        GenerateCode gc = new GenerateCode("DVD");
        
        if(gc.getCode().equals("invalid")) {
            JOptionPane.showMessageDialog(null, "Sucedio un error al crear este registro. Comunicate con el administrador.");
        }
        
        Dvd dvd = new Dvd();

        dvd.setCodigo(gc.getCode());
        dvd.setTitulo(titulo);
        dvd.setDuracion(duracion);
        dvd.setGeneroId(generoId);
        dvd.setTipoMaterialId(4);
        dvd.setCreadorId(directorId);
        
        boolean ok = dvdsController.createDvd(dvd);
        
        if(!ok) return;
        
        FrmMaterials form = new FrmMaterials(layoutPanel);
        JOptionPane.showMessageDialog(null, "Material guardado exitosamente");
        
        setLayoutContent(form);
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void existentDirectorRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existentDirectorRbActionPerformed
        handleDirectorMode();
    }//GEN-LAST:event_existentDirectorRbActionPerformed

    private void newDirectorRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDirectorRbActionPerformed
        handleDirectorMode();
    }//GEN-LAST:event_newDirectorRbActionPerformed

    private void tituloTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tituloTxtKeyReleased
        String text = tituloTxt.getText();
        boolean validLength = Validators.checkTextLength(text, 100);
        boolean validFormat = Validators.matchesRegex(text, Validators.getNoMaliciousCharactersRegex());
        
        if(!validLength) tituloTxt.setText(text.substring(0, 100));
        if (!validFormat) tituloTxt.setText(text.substring(0, text.length() - 1));
    }//GEN-LAST:event_tituloTxtKeyReleased

    private void directorTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_directorTxtKeyReleased
        String text = directorTxt.getText();
        boolean validLength = Validators.checkTextLength(text, 100);
        boolean validFormat = Validators.matchesRegex(text, Validators.getNoMaliciousCharactersRegex());
        
        if(!validLength) directorTxt.setText(text.substring(0, 100));
        if (!validFormat) directorTxt.setText(text.substring(0, text.length() - 1));
    }//GEN-LAST:event_directorTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup authorGroup;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> directorCb;
    private javax.swing.JTextField directorTxt;
    private javax.swing.JFormattedTextField duracionTxt;
    private javax.swing.ButtonGroup editorialGroup;
    private javax.swing.JRadioButton existentDirectorRb;
    private javax.swing.JComboBox<String> genderCb;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton newDirectorRb;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField tituloTxt;
    // End of variables declaration//GEN-END:variables
}
