package desafio2.views;

import desafio2.controllers.CtrlAuthors;
import desafio2.controllers.CtrlBooks;
import desafio2.controllers.CtrlEditorials;
import desafio2.controllers.CtrlMagazines;
import desafio2.helpers.GenerateCode;
import desafio2.helpers.Validators;
import desafio2.models.Author;
import desafio2.models.Book;
import desafio2.models.Editorial;
import desafio2.models.Magazine;
import desafio2.models.Periodicity;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class FrmCreateMagazines extends javax.swing.JPanel {
    private JPanel layoutPanel;
    private CtrlMagazines magazinesController;
    private CtrlEditorials editorialsController;    
    private List<Periodicity> periodicities;
    private List<Editorial> editorials;

    public FrmCreateMagazines(JPanel layoutPanel) {
        initComponents();
        
        magazinesController = new CtrlMagazines();
        editorialsController = new CtrlEditorials();
        
        getPeriodicity();
        getEditorials();
        
        this.layoutPanel = layoutPanel;
        
        handleEditorialMode();
        
        Validators.allowNumbers(unidadesTxt, 5);
    }
    
    private void setLayoutContent(JPanel content) {
        layoutPanel.removeAll();
        layoutPanel.add(content, BorderLayout.CENTER);
        layoutPanel.revalidate();
        layoutPanel.repaint();
    }
    
    private void getPeriodicity() {
        periodicities = magazinesController.getPeriodicites();
        
        periodicityCb.removeAllItems();
        periodicityCb.addItem("Selecciona la periodicidad");
        
        for (int i = 0; i < periodicities.size(); i++) {
            Periodicity periodicity = periodicities.get(i);
            
            periodicityCb.addItem(periodicity.getPeriodicidad());
        }
    }
    
    private void getEditorials() {
        editorials = editorialsController.getEditorials();
        
        editorialCb.removeAllItems();
        editorialCb.addItem("Selecciona una editorial");
        
        for (int i = 0; i < editorials.size(); i++) {
            Editorial editorial = editorials.get(i);
            
            editorialCb.addItem(editorial.getEditorial());
        }
    }
    
    private void handleEditorialMode() {
       boolean existentEditorial = existentEditorialRb.isSelected();
       boolean newEditorial = newEditorialRb.isSelected();
       
       editorialTxt.setVisible(newEditorial);
       editorialCb.setVisible(existentEditorial);
    }
    
    private int handlePeriodicityCreation() {
        int periodicidadId = 0;
        
        for (Periodicity p : periodicities) {
            if (p.getPeriodicidad().equals(periodicityCb.getSelectedItem())) {
                periodicidadId = p.getId();
                break;
            }
        }
        
        return periodicidadId;
    }
    
    private int handleEditorialCreation () {
        int editorialId = 0;
        boolean existentEditorial = existentEditorialRb.isSelected();
        
        if (existentEditorial) {
            for (Editorial e : editorials) {
                if (e.getEditorial().equals(editorialCb.getSelectedItem())) {
                    editorialId = e.getId();
                    break;
                }
            }
            
        } else {
            String editorialName = editorialTxt.getText().trim();
            
            if(editorialName.length() == 0) {
                JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
                return editorialId;
            }
            
            boolean ok = editorialsController.createEditorial(editorialName);
            if(!ok) return editorialId;
            
            Editorial newEditorial = editorialsController.getLatestEditorial();
            
            editorialId = newEditorial.getId();
        }
        
        return editorialId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorGroup = new javax.swing.ButtonGroup();
        editorialGroup = new javax.swing.ButtonGroup();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        periodicityCb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        existentEditorialRb = new javax.swing.JRadioButton();
        editorialCb = new javax.swing.JComboBox<>();
        newEditorialRb = new javax.swing.JRadioButton();
        editorialTxt = new javax.swing.JTextField();
        tituloTxt = new javax.swing.JTextField();
        unidadesTxt = new javax.swing.JTextField();
        fechaDc = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1100, 690));
        setMinimumSize(new java.awt.Dimension(1100, 690));
        setPreferredSize(new java.awt.Dimension(1100, 690));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Periodicidad:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Título:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        periodicityCb.setBackground(new java.awt.Color(255, 255, 255));
        periodicityCb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        periodicityCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        periodicityCb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jPanel1.add(periodicityCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 480, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Fecha de publicación:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Unidades disponibles:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 153, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Regresar");
        backBtn.setBorder(null);
        backBtn.setBorderPainted(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, 140, 40));

        saveBtn.setBackground(new java.awt.Color(0, 153, 255));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Guardar");
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 140, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nueva revista");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Editorial:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        existentEditorialRb.setBackground(new java.awt.Color(255, 255, 255));
        editorialGroup.add(existentEditorialRb);
        existentEditorialRb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        existentEditorialRb.setForeground(new java.awt.Color(102, 102, 102));
        existentEditorialRb.setSelected(true);
        existentEditorialRb.setText("Editorial existente");
        existentEditorialRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existentEditorialRbActionPerformed(evt);
            }
        });
        jPanel1.add(existentEditorialRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        editorialCb.setBackground(new java.awt.Color(255, 255, 255));
        editorialCb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        editorialCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editorialCb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        jPanel1.add(editorialCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 480, 30));

        newEditorialRb.setBackground(new java.awt.Color(255, 255, 255));
        editorialGroup.add(newEditorialRb);
        newEditorialRb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newEditorialRb.setForeground(new java.awt.Color(102, 102, 102));
        newEditorialRb.setText("Crear nueva editorial");
        newEditorialRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEditorialRbActionPerformed(evt);
            }
        });
        jPanel1.add(newEditorialRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        editorialTxt.setBackground(new java.awt.Color(255, 255, 255));
        editorialTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        editorialTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        editorialTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editorialTxtKeyReleased(evt);
            }
        });
        jPanel1.add(editorialTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 480, 30));

        tituloTxt.setBackground(new java.awt.Color(255, 255, 255));
        tituloTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tituloTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        tituloTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tituloTxtKeyReleased(evt);
            }
        });
        jPanel1.add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 480, 30));

        unidadesTxt.setBackground(new java.awt.Color(255, 255, 255));
        unidadesTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        unidadesTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        unidadesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unidadesTxtKeyReleased(evt);
            }
        });
        jPanel1.add(unidadesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 480, 30));

        fechaDc.setBackground(new java.awt.Color(255, 255, 255));
        fechaDc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        fechaDc.setDateFormatString("yyyy-MM-dd");
        fechaDc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(fechaDc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 480, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FrmSelectMaterialType form = new FrmSelectMaterialType(layoutPanel);
        setLayoutContent(form);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        String titulo = tituloTxt.getText().trim();        
        String unidades = unidadesTxt.getText();
        String fechaPub = sdf.format(fechaDc.getDate());
        int periodicidadId;
        int editorialId;        
        
        boolean validated = true;
        String[] fields = {titulo, fechaPub, unidades};
        
        for (int i = 0; i < fields.length; i++) {
            if (fields[i].length() == 0) {
                validated = false;
                break;
            }
        }
        
        if (!validated) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
            return;
        }
        
        periodicidadId = handlePeriodicityCreation();
        editorialId = handleEditorialCreation();
        
        if(periodicidadId == 0 || editorialId == 0) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacios.");
        }
        
        GenerateCode gc = new GenerateCode("Revista");
        
        if(gc.getCode().equals("invalid")) {
            JOptionPane.showMessageDialog(null, "Sucedio un error al crear este registro. Comunicate con el administrador.");
        }
        
        Magazine magazine = new Magazine();

        magazine.setCodigo(gc.getCode());
        magazine.setTitulo(titulo);
        magazine.setPeriodicidadId(periodicidadId);
        magazine.setTipoMaterialId(2);
        magazine.setFechaPublicacion(fechaPub);
        magazine.setUnidades(Integer.parseInt(unidades));
        magazine.setEditorialId(editorialId);
        
        boolean ok = magazinesController.createMagazine(magazine);
        
        if(!ok) return;
        
        FrmMaterials form = new FrmMaterials(layoutPanel);
        JOptionPane.showMessageDialog(null, "Material guardado exitosamente");
        
        setLayoutContent(form);
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void existentEditorialRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existentEditorialRbActionPerformed
        handleEditorialMode();
    }//GEN-LAST:event_existentEditorialRbActionPerformed

    private void newEditorialRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEditorialRbActionPerformed
        handleEditorialMode();
    }//GEN-LAST:event_newEditorialRbActionPerformed

    private void tituloTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tituloTxtKeyReleased
        String text = tituloTxt.getText();
        boolean validLength = Validators.checkTextLength(text, 100);
        boolean validFormat = Validators.matchesRegex(text, Validators.getNoMaliciousCharactersRegex());
        
        if(!validLength) tituloTxt.setText(text.substring(0, 100));
        if (!validFormat) tituloTxt.setText(text.substring(0, text.length() - 1));
    }//GEN-LAST:event_tituloTxtKeyReleased

    private void editorialTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editorialTxtKeyReleased
        String text = editorialTxt.getText();
        boolean validLength = Validators.checkTextLength(text, 100);
        boolean validFormat = Validators.matchesRegex(text, Validators.getNoMaliciousCharactersRegex());
        
        if(!validLength) editorialTxt.setText(text.substring(0, 100));
        if (!validFormat) editorialTxt.setText(text.substring(0, text.length() - 1));
    }//GEN-LAST:event_editorialTxtKeyReleased

    private void unidadesTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadesTxtKeyReleased
        
    }//GEN-LAST:event_unidadesTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup authorGroup;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> editorialCb;
    private javax.swing.ButtonGroup editorialGroup;
    private javax.swing.JTextField editorialTxt;
    private javax.swing.JRadioButton existentEditorialRb;
    private com.toedter.calendar.JDateChooser fechaDc;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton newEditorialRb;
    private javax.swing.JComboBox<String> periodicityCb;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField tituloTxt;
    private javax.swing.JTextField unidadesTxt;
    // End of variables declaration//GEN-END:variables
}
