/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafio2.views;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Eduardo
 */
public class FrmLayout extends javax.swing.JFrame {
    private Color pressedButtonColor = new Color(0, 107, 178);
    private Color defaultButtonColor = new Color(0, 153, 255);
    private JComponent selectedButton;
    private List<JPanel> allowedButtons = new ArrayList<JPanel>();
    
    public FrmLayout() {
        initComponents();
        initAllowedButtons();
        this.setLocationRelativeTo(null);
        
        FrmMaterials materialPanel = new FrmMaterials();
        
        setContent(materialPanel);
        setActiveButton(materialsBtn);
        setCustomTitle("Mediateca | Materiales");
    }
    
    private void setContent(JPanel content) {
        contentPanel.removeAll();
        contentPanel.add(content, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }
    
    private void setActiveButton(JComponent button) {
        Consumer<JPanel> setDefaultStyle = buttonTobeUpdated -> buttonTobeUpdated.setBackground(defaultButtonColor);
        allowedButtons.forEach(setDefaultStyle);
        
        button.setBackground(pressedButtonColor);
        selectedButton = button;
    }
    
    private void initAllowedButtons() {
        allowedButtons.add(materialsBtn);
        allowedButtons.add(editorialBtn);
        allowedButtons.add(creatorsBtn);
    }
    
    private void setCustomTitle(String title) {
        titleLbl.setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        materialsBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        creatorsBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editorialBtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        actionBar = new javax.swing.JPanel();
        closeBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(0, 153, 255));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materialsBtn.setBackground(new java.awt.Color(0, 153, 255));
        materialsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        materialsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materialsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                materialsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                materialsBtnMouseExited(evt);
            }
        });
        materialsBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Materiales");
        materialsBtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 5, 110, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desafio2/resources/materials.png"))); // NOI18N
        materialsBtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 60, 50));

        sidebar.add(materialsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 40));

        creatorsBtn.setBackground(new java.awt.Color(0, 153, 255));
        creatorsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creatorsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatorsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creatorsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creatorsBtnMouseExited(evt);
            }
        });
        creatorsBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Creadores");
        creatorsBtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 5, 110, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desafio2/resources/authors.png"))); // NOI18N
        creatorsBtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 60, 50));

        sidebar.add(creatorsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 40));

        editorialBtn.setBackground(new java.awt.Color(0, 153, 255));
        editorialBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editorialBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editorialBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editorialBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editorialBtnMouseExited(evt);
            }
        });
        editorialBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Editoriales");
        editorialBtn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 5, 110, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desafio2/resources/editorial.png"))); // NOI18N
        editorialBtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 60, 50));

        sidebar.add(editorialBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mediateca");
        sidebar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 160, 50));

        bg.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

        actionBar.setBackground(new java.awt.Color(230, 230, 230));
        actionBar.setPreferredSize(new java.awt.Dimension(1100, 35));
        actionBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeBtn.setBackground(new java.awt.Color(255, 0, 102));
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeBtnMousePressed(evt);
            }
        });
        closeBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(230, 230, 230));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        closeBtn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        actionBar.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 30, 30));

        titleLbl.setBackground(new java.awt.Color(0, 0, 0));
        titleLbl.setForeground(new java.awt.Color(0, 0, 0));
        titleLbl.setText("Title");
        actionBar.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -4, 1000, 40));

        bg.add(actionBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1100, 30));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        bg.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 1100, 690));

        getContentPane().add(bg, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMousePressed
        int response = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas salír del programa?", "Confirmación", JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnMousePressed

    private void materialsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialsBtnMouseEntered
        if(!selectedButton.equals(materialsBtn)) {
            materialsBtn.setBackground(this.pressedButtonColor);
        }
    }//GEN-LAST:event_materialsBtnMouseEntered

    private void materialsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialsBtnMouseExited
        if(!selectedButton.equals(materialsBtn)) {
            materialsBtn.setBackground(this.defaultButtonColor);
        }
    }//GEN-LAST:event_materialsBtnMouseExited

    private void creatorsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatorsBtnMouseEntered
        if (!selectedButton.equals(creatorsBtn)) {
            this.creatorsBtn.setBackground(this.pressedButtonColor);
        }
    }//GEN-LAST:event_creatorsBtnMouseEntered

    private void creatorsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatorsBtnMouseExited
        if (!selectedButton.equals(creatorsBtn)) {
            this.creatorsBtn.setBackground(this.defaultButtonColor);
        }
    }//GEN-LAST:event_creatorsBtnMouseExited

    private void editorialBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editorialBtnMouseEntered
        if (!selectedButton.equals(editorialBtn)) {
            this.editorialBtn.setBackground(this.pressedButtonColor);
        }
    }//GEN-LAST:event_editorialBtnMouseEntered

    private void editorialBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editorialBtnMouseExited
        if (!selectedButton.equals(editorialBtn)) {
            this.editorialBtn.setBackground(this.defaultButtonColor);
        }
    }//GEN-LAST:event_editorialBtnMouseExited

    private void materialsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materialsBtnMouseClicked
        FrmMaterials materialPanel = new FrmMaterials();
        setContent(materialPanel);
        setActiveButton(materialsBtn);
        setCustomTitle("Mediateca | Materiales");
    }//GEN-LAST:event_materialsBtnMouseClicked

    private void creatorsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatorsBtnMouseClicked
        FrmAuthors authorsPanel = new FrmAuthors();
        setContent(authorsPanel);
        setActiveButton(creatorsBtn);
        setCustomTitle("Mediateca | Creadores");
    }//GEN-LAST:event_creatorsBtnMouseClicked

    private void editorialBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editorialBtnMouseClicked
        FrmEditorials editorialsPanel = new FrmEditorials();
        setContent(editorialsPanel);
        setActiveButton(editorialBtn);
        setCustomTitle("Mediateca | Editoriales");
    }//GEN-LAST:event_editorialBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionBar;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel closeBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel creatorsBtn;
    private javax.swing.JPanel editorialBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel materialsBtn;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
